import { fileURLToPath } from 'node:url'
import { defineConfig } from 'vite-plus'
import glsl from 'vite-plugin-glsl'

export default defineConfig({
  fmt: {
    semi: false,
    singleQuote: true,
    ignorePatterns: [],
  },
  staged: {
    '*': 'vp check --fix',
  },
  lint: {
    plugins: ['oxc', 'typescript', 'unicorn', 'react', 'node', 'jsdoc', 'import'],
    jsPlugins: [
      'eslint-plugin-antfu',
      'eslint-plugin-unused-imports',
      'eslint-plugin-eslint-comments',
      'eslint-plugin-command',
      'eslint-plugin-perfectionist',
      '@stylistic/eslint-plugin',
      'eslint-plugin-regexp',
    ],
    categories: {
      correctness: 'warn',
    },
    options: {
      typeAware: true,
      typeCheck: true,
    },
    env: {
      builtin: true,
      commonjs: true,
      es2024: true,
    },
    globals: {
      AbortController: 'readonly',
      AbortSignal: 'readonly',
      AbsoluteOrientationSensor: 'readonly',
      AbstractRange: 'readonly',
      Accelerometer: 'readonly',
      addEventListener: 'readonly',
      ai: 'readonly',
      AI: 'readonly',
      AITextSession: 'readonly',
      alert: 'readonly',
      AnalyserNode: 'readonly',
      Animation: 'readonly',
      AnimationEffect: 'readonly',
      AnimationEvent: 'readonly',
      AnimationPlaybackEvent: 'readonly',
      AnimationTimeline: 'readonly',
      atob: 'readonly',
      Attr: 'readonly',
      Audio: 'readonly',
      AudioBuffer: 'readonly',
      AudioBufferSourceNode: 'readonly',
      AudioContext: 'readonly',
      AudioData: 'readonly',
      AudioDecoder: 'readonly',
      AudioDestinationNode: 'readonly',
      AudioEncoder: 'readonly',
      AudioListener: 'readonly',
      AudioNode: 'readonly',
      AudioParam: 'readonly',
      AudioParamMap: 'readonly',
      AudioProcessingEvent: 'readonly',
      AudioScheduledSourceNode: 'readonly',
      AudioSinkInfo: 'readonly',
      AudioWorklet: 'readonly',
      AudioWorkletGlobalScope: 'readonly',
      AudioWorkletNode: 'readonly',
      AudioWorkletProcessor: 'readonly',
      AuthenticatorAssertionResponse: 'readonly',
      AuthenticatorAttestationResponse: 'readonly',
      AuthenticatorResponse: 'readonly',
      BackgroundFetchManager: 'readonly',
      BackgroundFetchRecord: 'readonly',
      BackgroundFetchRegistration: 'readonly',
      BarcodeDetector: 'readonly',
      BarProp: 'readonly',
      BaseAudioContext: 'readonly',
      BatteryManager: 'readonly',
      BeforeUnloadEvent: 'readonly',
      BiquadFilterNode: 'readonly',
      Blob: 'readonly',
      BlobEvent: 'readonly',
      Bluetooth: 'readonly',
      BluetoothCharacteristicProperties: 'readonly',
      BluetoothDevice: 'readonly',
      BluetoothRemoteGATTCharacteristic: 'readonly',
      BluetoothRemoteGATTDescriptor: 'readonly',
      BluetoothRemoteGATTServer: 'readonly',
      BluetoothRemoteGATTService: 'readonly',
      BluetoothUUID: 'readonly',
      blur: 'readonly',
      BroadcastChannel: 'readonly',
      BrowserCaptureMediaStreamTrack: 'readonly',
      btoa: 'readonly',
      ByteLengthQueuingStrategy: 'readonly',
      Cache: 'readonly',
      caches: 'readonly',
      CacheStorage: 'readonly',
      cancelAnimationFrame: 'readonly',
      cancelIdleCallback: 'readonly',
      CanvasCaptureMediaStream: 'readonly',
      CanvasCaptureMediaStreamTrack: 'readonly',
      CanvasGradient: 'readonly',
      CanvasPattern: 'readonly',
      CanvasRenderingContext2D: 'readonly',
      CaptureController: 'readonly',
      CaretPosition: 'readonly',
      CDATASection: 'readonly',
      ChannelMergerNode: 'readonly',
      ChannelSplitterNode: 'readonly',
      ChapterInformation: 'readonly',
      CharacterBoundsUpdateEvent: 'readonly',
      CharacterData: 'readonly',
      clearInterval: 'readonly',
      clearTimeout: 'readonly',
      clientInformation: 'readonly',
      Clipboard: 'readonly',
      ClipboardEvent: 'readonly',
      ClipboardItem: 'readonly',
      close: 'readonly',
      closed: 'readonly',
      CloseEvent: 'readonly',
      CloseWatcher: 'readonly',
      Comment: 'readonly',
      CompositionEvent: 'readonly',
      CompressionStream: 'readonly',
      confirm: 'readonly',
      console: 'readonly',
      ConstantSourceNode: 'readonly',
      ContentVisibilityAutoStateChangeEvent: 'readonly',
      ConvolverNode: 'readonly',
      CookieChangeEvent: 'readonly',
      CookieDeprecationLabel: 'readonly',
      cookieStore: 'readonly',
      CookieStore: 'readonly',
      CookieStoreManager: 'readonly',
      CountQueuingStrategy: 'readonly',
      createImageBitmap: 'readonly',
      Credential: 'readonly',
      credentialless: 'readonly',
      CredentialsContainer: 'readonly',
      CropTarget: 'readonly',
      crossOriginIsolated: 'readonly',
      crypto: 'readonly',
      Crypto: 'readonly',
      CryptoKey: 'readonly',
      CSS: 'readonly',
      CSSAnimation: 'readonly',
      CSSConditionRule: 'readonly',
      CSSContainerRule: 'readonly',
      CSSCounterStyleRule: 'readonly',
      CSSFontFaceRule: 'readonly',
      CSSFontFeatureValuesRule: 'readonly',
      CSSFontPaletteValuesRule: 'readonly',
      CSSGroupingRule: 'readonly',
      CSSImageValue: 'readonly',
      CSSImportRule: 'readonly',
      CSSKeyframeRule: 'readonly',
      CSSKeyframesRule: 'readonly',
      CSSKeywordValue: 'readonly',
      CSSLayerBlockRule: 'readonly',
      CSSLayerStatementRule: 'readonly',
      CSSMarginRule: 'readonly',
      CSSMathClamp: 'readonly',
      CSSMathInvert: 'readonly',
      CSSMathMax: 'readonly',
      CSSMathMin: 'readonly',
      CSSMathNegate: 'readonly',
      CSSMathProduct: 'readonly',
      CSSMathSum: 'readonly',
      CSSMathValue: 'readonly',
      CSSMatrixComponent: 'readonly',
      CSSMediaRule: 'readonly',
      CSSNamespaceRule: 'readonly',
      CSSNestedDeclarations: 'readonly',
      CSSNumericArray: 'readonly',
      CSSNumericValue: 'readonly',
      CSSPageDescriptors: 'readonly',
      CSSPageRule: 'readonly',
      CSSPerspective: 'readonly',
      CSSPositionTryDescriptors: 'readonly',
      CSSPositionTryRule: 'readonly',
      CSSPositionValue: 'readonly',
      CSSPropertyRule: 'readonly',
      CSSRotate: 'readonly',
      CSSRule: 'readonly',
      CSSRuleList: 'readonly',
      CSSScale: 'readonly',
      CSSScopeRule: 'readonly',
      CSSSkew: 'readonly',
      CSSSkewX: 'readonly',
      CSSSkewY: 'readonly',
      CSSStartingStyleRule: 'readonly',
      CSSStyleDeclaration: 'readonly',
      CSSStyleRule: 'readonly',
      CSSStyleSheet: 'readonly',
      CSSStyleValue: 'readonly',
      CSSSupportsRule: 'readonly',
      CSSTransformComponent: 'readonly',
      CSSTransformValue: 'readonly',
      CSSTransition: 'readonly',
      CSSTranslate: 'readonly',
      CSSUnitValue: 'readonly',
      CSSUnparsedValue: 'readonly',
      CSSVariableReferenceValue: 'readonly',
      CSSViewTransitionRule: 'readonly',
      currentFrame: 'readonly',
      currentTime: 'readonly',
      CustomElementRegistry: 'readonly',
      customElements: 'readonly',
      CustomEvent: 'readonly',
      CustomStateSet: 'readonly',
      DataTransfer: 'readonly',
      DataTransferItem: 'readonly',
      DataTransferItemList: 'readonly',
      DecompressionStream: 'readonly',
      DelayNode: 'readonly',
      DelegatedInkTrailPresenter: 'readonly',
      DeviceMotionEvent: 'readonly',
      DeviceMotionEventAcceleration: 'readonly',
      DeviceMotionEventRotationRate: 'readonly',
      DeviceOrientationEvent: 'readonly',
      devicePixelRatio: 'readonly',
      dispatchEvent: 'readonly',
      document: 'readonly',
      Document: 'readonly',
      DocumentFragment: 'readonly',
      documentPictureInPicture: 'readonly',
      DocumentPictureInPicture: 'readonly',
      DocumentPictureInPictureEvent: 'readonly',
      DocumentTimeline: 'readonly',
      DocumentType: 'readonly',
      DOMError: 'readonly',
      DOMException: 'readonly',
      DOMImplementation: 'readonly',
      DOMMatrix: 'readonly',
      DOMMatrixReadOnly: 'readonly',
      DOMParser: 'readonly',
      DOMPoint: 'readonly',
      DOMPointReadOnly: 'readonly',
      DOMQuad: 'readonly',
      DOMRect: 'readonly',
      DOMRectList: 'readonly',
      DOMRectReadOnly: 'readonly',
      DOMStringList: 'readonly',
      DOMStringMap: 'readonly',
      DOMTokenList: 'readonly',
      DragEvent: 'readonly',
      DynamicsCompressorNode: 'readonly',
      EditContext: 'readonly',
      Element: 'readonly',
      ElementInternals: 'readonly',
      EncodedAudioChunk: 'readonly',
      EncodedVideoChunk: 'readonly',
      ErrorEvent: 'readonly',
      event: 'readonly',
      Event: 'readonly',
      EventCounts: 'readonly',
      EventSource: 'readonly',
      EventTarget: 'readonly',
      external: 'readonly',
      External: 'readonly',
      EyeDropper: 'readonly',
      FeaturePolicy: 'readonly',
      FederatedCredential: 'readonly',
      fence: 'readonly',
      Fence: 'readonly',
      FencedFrameConfig: 'readonly',
      fetch: 'readonly',
      fetchLater: 'readonly',
      FetchLaterResult: 'readonly',
      File: 'readonly',
      FileList: 'readonly',
      FileReader: 'readonly',
      FileSystem: 'readonly',
      FileSystemDirectoryEntry: 'readonly',
      FileSystemDirectoryHandle: 'readonly',
      FileSystemDirectoryReader: 'readonly',
      FileSystemEntry: 'readonly',
      FileSystemFileEntry: 'readonly',
      FileSystemFileHandle: 'readonly',
      FileSystemHandle: 'readonly',
      FileSystemWritableFileStream: 'readonly',
      find: 'readonly',
      focus: 'readonly',
      FocusEvent: 'readonly',
      FontData: 'readonly',
      FontFace: 'readonly',
      FontFaceSet: 'readonly',
      FontFaceSetLoadEvent: 'readonly',
      FormData: 'readonly',
      FormDataEvent: 'readonly',
      FragmentDirective: 'readonly',
      frameElement: 'readonly',
      frames: 'readonly',
      GainNode: 'readonly',
      Gamepad: 'readonly',
      GamepadAxisMoveEvent: 'readonly',
      GamepadButton: 'readonly',
      GamepadButtonEvent: 'readonly',
      GamepadEvent: 'readonly',
      GamepadHapticActuator: 'readonly',
      GamepadPose: 'readonly',
      Geolocation: 'readonly',
      GeolocationCoordinates: 'readonly',
      GeolocationPosition: 'readonly',
      GeolocationPositionError: 'readonly',
      getComputedStyle: 'readonly',
      getScreenDetails: 'readonly',
      getSelection: 'readonly',
      GPU: 'readonly',
      GPUAdapter: 'readonly',
      GPUAdapterInfo: 'readonly',
      GPUBindGroup: 'readonly',
      GPUBindGroupLayout: 'readonly',
      GPUBuffer: 'readonly',
      GPUBufferUsage: 'readonly',
      GPUCanvasContext: 'readonly',
      GPUColorWrite: 'readonly',
      GPUCommandBuffer: 'readonly',
      GPUCommandEncoder: 'readonly',
      GPUCompilationInfo: 'readonly',
      GPUCompilationMessage: 'readonly',
      GPUComputePassEncoder: 'readonly',
      GPUComputePipeline: 'readonly',
      GPUDevice: 'readonly',
      GPUDeviceLostInfo: 'readonly',
      GPUError: 'readonly',
      GPUExternalTexture: 'readonly',
      GPUInternalError: 'readonly',
      GPUMapMode: 'readonly',
      GPUOutOfMemoryError: 'readonly',
      GPUPipelineError: 'readonly',
      GPUPipelineLayout: 'readonly',
      GPUQuerySet: 'readonly',
      GPUQueue: 'readonly',
      GPURenderBundle: 'readonly',
      GPURenderBundleEncoder: 'readonly',
      GPURenderPassEncoder: 'readonly',
      GPURenderPipeline: 'readonly',
      GPUSampler: 'readonly',
      GPUShaderModule: 'readonly',
      GPUShaderStage: 'readonly',
      GPUSupportedFeatures: 'readonly',
      GPUSupportedLimits: 'readonly',
      GPUTexture: 'readonly',
      GPUTextureUsage: 'readonly',
      GPUTextureView: 'readonly',
      GPUUncapturedErrorEvent: 'readonly',
      GPUValidationError: 'readonly',
      GravitySensor: 'readonly',
      Gyroscope: 'readonly',
      HashChangeEvent: 'readonly',
      Headers: 'readonly',
      HID: 'readonly',
      HIDConnectionEvent: 'readonly',
      HIDDevice: 'readonly',
      HIDInputReportEvent: 'readonly',
      Highlight: 'readonly',
      HighlightRegistry: 'readonly',
      history: 'readonly',
      History: 'readonly',
      HTMLAllCollection: 'readonly',
      HTMLAnchorElement: 'readonly',
      HTMLAreaElement: 'readonly',
      HTMLAudioElement: 'readonly',
      HTMLBaseElement: 'readonly',
      HTMLBodyElement: 'readonly',
      HTMLBRElement: 'readonly',
      HTMLButtonElement: 'readonly',
      HTMLCanvasElement: 'readonly',
      HTMLCollection: 'readonly',
      HTMLDataElement: 'readonly',
      HTMLDataListElement: 'readonly',
      HTMLDetailsElement: 'readonly',
      HTMLDialogElement: 'readonly',
      HTMLDirectoryElement: 'readonly',
      HTMLDivElement: 'readonly',
      HTMLDListElement: 'readonly',
      HTMLDocument: 'readonly',
      HTMLElement: 'readonly',
      HTMLEmbedElement: 'readonly',
      HTMLFencedFrameElement: 'readonly',
      HTMLFieldSetElement: 'readonly',
      HTMLFontElement: 'readonly',
      HTMLFormControlsCollection: 'readonly',
      HTMLFormElement: 'readonly',
      HTMLFrameElement: 'readonly',
      HTMLFrameSetElement: 'readonly',
      HTMLHeadElement: 'readonly',
      HTMLHeadingElement: 'readonly',
      HTMLHRElement: 'readonly',
      HTMLHtmlElement: 'readonly',
      HTMLIFrameElement: 'readonly',
      HTMLImageElement: 'readonly',
      HTMLInputElement: 'readonly',
      HTMLLabelElement: 'readonly',
      HTMLLegendElement: 'readonly',
      HTMLLIElement: 'readonly',
      HTMLLinkElement: 'readonly',
      HTMLMapElement: 'readonly',
      HTMLMarqueeElement: 'readonly',
      HTMLMediaElement: 'readonly',
      HTMLMenuElement: 'readonly',
      HTMLMetaElement: 'readonly',
      HTMLMeterElement: 'readonly',
      HTMLModElement: 'readonly',
      HTMLObjectElement: 'readonly',
      HTMLOListElement: 'readonly',
      HTMLOptGroupElement: 'readonly',
      HTMLOptionElement: 'readonly',
      HTMLOptionsCollection: 'readonly',
      HTMLOutputElement: 'readonly',
      HTMLParagraphElement: 'readonly',
      HTMLParamElement: 'readonly',
      HTMLPictureElement: 'readonly',
      HTMLPreElement: 'readonly',
      HTMLProgressElement: 'readonly',
      HTMLQuoteElement: 'readonly',
      HTMLScriptElement: 'readonly',
      HTMLSelectElement: 'readonly',
      HTMLSlotElement: 'readonly',
      HTMLSourceElement: 'readonly',
      HTMLSpanElement: 'readonly',
      HTMLStyleElement: 'readonly',
      HTMLTableCaptionElement: 'readonly',
      HTMLTableCellElement: 'readonly',
      HTMLTableColElement: 'readonly',
      HTMLTableElement: 'readonly',
      HTMLTableRowElement: 'readonly',
      HTMLTableSectionElement: 'readonly',
      HTMLTemplateElement: 'readonly',
      HTMLTextAreaElement: 'readonly',
      HTMLTimeElement: 'readonly',
      HTMLTitleElement: 'readonly',
      HTMLTrackElement: 'readonly',
      HTMLUListElement: 'readonly',
      HTMLUnknownElement: 'readonly',
      HTMLVideoElement: 'readonly',
      IDBCursor: 'readonly',
      IDBCursorWithValue: 'readonly',
      IDBDatabase: 'readonly',
      IDBFactory: 'readonly',
      IDBIndex: 'readonly',
      IDBKeyRange: 'readonly',
      IDBObjectStore: 'readonly',
      IDBOpenDBRequest: 'readonly',
      IDBRequest: 'readonly',
      IDBTransaction: 'readonly',
      IDBVersionChangeEvent: 'readonly',
      IdentityCredential: 'readonly',
      IdentityCredentialError: 'readonly',
      IdentityProvider: 'readonly',
      IdleDeadline: 'readonly',
      IdleDetector: 'readonly',
      IIRFilterNode: 'readonly',
      Image: 'readonly',
      ImageBitmap: 'readonly',
      ImageBitmapRenderingContext: 'readonly',
      ImageCapture: 'readonly',
      ImageData: 'readonly',
      ImageDecoder: 'readonly',
      ImageTrack: 'readonly',
      ImageTrackList: 'readonly',
      indexedDB: 'readonly',
      Ink: 'readonly',
      innerHeight: 'readonly',
      innerWidth: 'readonly',
      InputDeviceCapabilities: 'readonly',
      InputDeviceInfo: 'readonly',
      InputEvent: 'readonly',
      IntersectionObserver: 'readonly',
      IntersectionObserverEntry: 'readonly',
      isSecureContext: 'readonly',
      Keyboard: 'readonly',
      KeyboardEvent: 'readonly',
      KeyboardLayoutMap: 'readonly',
      KeyframeEffect: 'readonly',
      LargestContentfulPaint: 'readonly',
      LaunchParams: 'readonly',
      launchQueue: 'readonly',
      LaunchQueue: 'readonly',
      LayoutShift: 'readonly',
      LayoutShiftAttribution: 'readonly',
      length: 'readonly',
      LinearAccelerationSensor: 'readonly',
      localStorage: 'readonly',
      location: 'writable',
      Location: 'readonly',
      locationbar: 'readonly',
      Lock: 'readonly',
      LockManager: 'readonly',
      matchMedia: 'readonly',
      MathMLElement: 'readonly',
      MediaCapabilities: 'readonly',
      MediaCapabilitiesInfo: 'readonly',
      MediaDeviceInfo: 'readonly',
      MediaDevices: 'readonly',
      MediaElementAudioSourceNode: 'readonly',
      MediaEncryptedEvent: 'readonly',
      MediaError: 'readonly',
      MediaKeyError: 'readonly',
      MediaKeyMessageEvent: 'readonly',
      MediaKeys: 'readonly',
      MediaKeySession: 'readonly',
      MediaKeyStatusMap: 'readonly',
      MediaKeySystemAccess: 'readonly',
      MediaList: 'readonly',
      MediaMetadata: 'readonly',
      MediaQueryList: 'readonly',
      MediaQueryListEvent: 'readonly',
      MediaRecorder: 'readonly',
      MediaRecorderErrorEvent: 'readonly',
      MediaSession: 'readonly',
      MediaSource: 'readonly',
      MediaSourceHandle: 'readonly',
      MediaStream: 'readonly',
      MediaStreamAudioDestinationNode: 'readonly',
      MediaStreamAudioSourceNode: 'readonly',
      MediaStreamEvent: 'readonly',
      MediaStreamTrack: 'readonly',
      MediaStreamTrackAudioSourceNode: 'readonly',
      MediaStreamTrackAudioStats: 'readonly',
      MediaStreamTrackEvent: 'readonly',
      MediaStreamTrackGenerator: 'readonly',
      MediaStreamTrackProcessor: 'readonly',
      MediaStreamTrackVideoStats: 'readonly',
      menubar: 'readonly',
      MessageChannel: 'readonly',
      MessageEvent: 'readonly',
      MessagePort: 'readonly',
      MIDIAccess: 'readonly',
      MIDIConnectionEvent: 'readonly',
      MIDIInput: 'readonly',
      MIDIInputMap: 'readonly',
      MIDIMessageEvent: 'readonly',
      MIDIOutput: 'readonly',
      MIDIOutputMap: 'readonly',
      MIDIPort: 'readonly',
      MimeType: 'readonly',
      MimeTypeArray: 'readonly',
      model: 'readonly',
      ModelGenericSession: 'readonly',
      ModelManager: 'readonly',
      MouseEvent: 'readonly',
      moveBy: 'readonly',
      moveTo: 'readonly',
      MutationEvent: 'readonly',
      MutationObserver: 'readonly',
      MutationRecord: 'readonly',
      name: 'readonly',
      NamedNodeMap: 'readonly',
      NavigateEvent: 'readonly',
      navigation: 'readonly',
      Navigation: 'readonly',
      NavigationActivation: 'readonly',
      NavigationCurrentEntryChangeEvent: 'readonly',
      NavigationDestination: 'readonly',
      NavigationHistoryEntry: 'readonly',
      NavigationPreloadManager: 'readonly',
      NavigationTransition: 'readonly',
      navigator: 'readonly',
      Navigator: 'readonly',
      NavigatorLogin: 'readonly',
      NavigatorManagedData: 'readonly',
      NavigatorUAData: 'readonly',
      NetworkInformation: 'readonly',
      Node: 'readonly',
      NodeFilter: 'readonly',
      NodeIterator: 'readonly',
      NodeList: 'readonly',
      Notification: 'readonly',
      NotifyPaintEvent: 'readonly',
      NotRestoredReasonDetails: 'readonly',
      NotRestoredReasons: 'readonly',
      OfflineAudioCompletionEvent: 'readonly',
      OfflineAudioContext: 'readonly',
      offscreenBuffering: 'readonly',
      OffscreenCanvas: 'readonly',
      OffscreenCanvasRenderingContext2D: 'readonly',
      onabort: 'writable',
      onafterprint: 'writable',
      onanimationcancel: 'writable',
      onanimationend: 'writable',
      onanimationiteration: 'writable',
      onanimationstart: 'writable',
      onappinstalled: 'writable',
      onauxclick: 'writable',
      onbeforeinput: 'writable',
      onbeforeinstallprompt: 'writable',
      onbeforematch: 'writable',
      onbeforeprint: 'writable',
      onbeforetoggle: 'writable',
      onbeforeunload: 'writable',
      onbeforexrselect: 'writable',
      onblur: 'writable',
      oncancel: 'writable',
      oncanplay: 'writable',
      oncanplaythrough: 'writable',
      onchange: 'writable',
      onclick: 'writable',
      onclose: 'writable',
      oncontentvisibilityautostatechange: 'writable',
      oncontextlost: 'writable',
      oncontextmenu: 'writable',
      oncontextrestored: 'writable',
      oncopy: 'writable',
      oncuechange: 'writable',
      oncut: 'writable',
      ondblclick: 'writable',
      ondevicemotion: 'writable',
      ondeviceorientation: 'writable',
      ondeviceorientationabsolute: 'writable',
      ondrag: 'writable',
      ondragend: 'writable',
      ondragenter: 'writable',
      ondragleave: 'writable',
      ondragover: 'writable',
      ondragstart: 'writable',
      ondrop: 'writable',
      ondurationchange: 'writable',
      onemptied: 'writable',
      onended: 'writable',
      onerror: 'writable',
      onfocus: 'writable',
      onformdata: 'writable',
      ongamepadconnected: 'writable',
      ongamepaddisconnected: 'writable',
      ongotpointercapture: 'writable',
      onhashchange: 'writable',
      oninput: 'writable',
      oninvalid: 'writable',
      onkeydown: 'writable',
      onkeypress: 'writable',
      onkeyup: 'writable',
      onlanguagechange: 'writable',
      onload: 'writable',
      onloadeddata: 'writable',
      onloadedmetadata: 'writable',
      onloadstart: 'writable',
      onlostpointercapture: 'writable',
      onmessage: 'writable',
      onmessageerror: 'writable',
      onmousedown: 'writable',
      onmouseenter: 'writable',
      onmouseleave: 'writable',
      onmousemove: 'writable',
      onmouseout: 'writable',
      onmouseover: 'writable',
      onmouseup: 'writable',
      onmousewheel: 'writable',
      onoffline: 'writable',
      ononline: 'writable',
      onpagehide: 'writable',
      onpagereveal: 'writable',
      onpageshow: 'writable',
      onpageswap: 'writable',
      onpaste: 'writable',
      onpause: 'writable',
      onplay: 'writable',
      onplaying: 'writable',
      onpointercancel: 'writable',
      onpointerdown: 'writable',
      onpointerenter: 'writable',
      onpointerleave: 'writable',
      onpointermove: 'writable',
      onpointerout: 'writable',
      onpointerover: 'writable',
      onpointerrawupdate: 'writable',
      onpointerup: 'writable',
      onpopstate: 'writable',
      onprogress: 'writable',
      onratechange: 'writable',
      onrejectionhandled: 'writable',
      onreset: 'writable',
      onresize: 'writable',
      onscroll: 'writable',
      onscrollend: 'writable',
      onscrollsnapchange: 'writable',
      onscrollsnapchanging: 'writable',
      onsearch: 'writable',
      onsecuritypolicyviolation: 'writable',
      onseeked: 'writable',
      onseeking: 'writable',
      onselect: 'writable',
      onselectionchange: 'writable',
      onselectstart: 'writable',
      onslotchange: 'writable',
      onstalled: 'writable',
      onstorage: 'writable',
      onsubmit: 'writable',
      onsuspend: 'writable',
      ontimeupdate: 'writable',
      ontoggle: 'writable',
      ontransitioncancel: 'writable',
      ontransitionend: 'writable',
      ontransitionrun: 'writable',
      ontransitionstart: 'writable',
      onunhandledrejection: 'writable',
      onunload: 'writable',
      onvolumechange: 'writable',
      onwaiting: 'writable',
      onwheel: 'writable',
      open: 'readonly',
      opener: 'readonly',
      Option: 'readonly',
      OrientationSensor: 'readonly',
      origin: 'readonly',
      originAgentCluster: 'readonly',
      OscillatorNode: 'readonly',
      OTPCredential: 'readonly',
      outerHeight: 'readonly',
      outerWidth: 'readonly',
      OverconstrainedError: 'readonly',
      PageRevealEvent: 'readonly',
      PageSwapEvent: 'readonly',
      PageTransitionEvent: 'readonly',
      pageXOffset: 'readonly',
      pageYOffset: 'readonly',
      PannerNode: 'readonly',
      parent: 'readonly',
      PasswordCredential: 'readonly',
      Path2D: 'readonly',
      PaymentAddress: 'readonly',
      PaymentManager: 'readonly',
      PaymentMethodChangeEvent: 'readonly',
      PaymentRequest: 'readonly',
      PaymentRequestUpdateEvent: 'readonly',
      PaymentResponse: 'readonly',
      performance: 'readonly',
      Performance: 'readonly',
      PerformanceElementTiming: 'readonly',
      PerformanceEntry: 'readonly',
      PerformanceEventTiming: 'readonly',
      PerformanceLongAnimationFrameTiming: 'readonly',
      PerformanceLongTaskTiming: 'readonly',
      PerformanceMark: 'readonly',
      PerformanceMeasure: 'readonly',
      PerformanceNavigation: 'readonly',
      PerformanceNavigationTiming: 'readonly',
      PerformanceObserver: 'readonly',
      PerformanceObserverEntryList: 'readonly',
      PerformancePaintTiming: 'readonly',
      PerformanceResourceTiming: 'readonly',
      PerformanceScriptTiming: 'readonly',
      PerformanceServerTiming: 'readonly',
      PerformanceTiming: 'readonly',
      PeriodicSyncManager: 'readonly',
      PeriodicWave: 'readonly',
      Permissions: 'readonly',
      PermissionStatus: 'readonly',
      PERSISTENT: 'readonly',
      personalbar: 'readonly',
      PictureInPictureEvent: 'readonly',
      PictureInPictureWindow: 'readonly',
      Plugin: 'readonly',
      PluginArray: 'readonly',
      PointerEvent: 'readonly',
      PopStateEvent: 'readonly',
      postMessage: 'readonly',
      Presentation: 'readonly',
      PresentationAvailability: 'readonly',
      PresentationConnection: 'readonly',
      PresentationConnectionAvailableEvent: 'readonly',
      PresentationConnectionCloseEvent: 'readonly',
      PresentationConnectionList: 'readonly',
      PresentationReceiver: 'readonly',
      PresentationRequest: 'readonly',
      PressureObserver: 'readonly',
      PressureRecord: 'readonly',
      print: 'readonly',
      ProcessingInstruction: 'readonly',
      Profiler: 'readonly',
      ProgressEvent: 'readonly',
      PromiseRejectionEvent: 'readonly',
      prompt: 'readonly',
      ProtectedAudience: 'readonly',
      PublicKeyCredential: 'readonly',
      PushManager: 'readonly',
      PushSubscription: 'readonly',
      PushSubscriptionOptions: 'readonly',
      queryLocalFonts: 'readonly',
      queueMicrotask: 'readonly',
      RadioNodeList: 'readonly',
      Range: 'readonly',
      ReadableByteStreamController: 'readonly',
      ReadableStream: 'readonly',
      ReadableStreamBYOBReader: 'readonly',
      ReadableStreamBYOBRequest: 'readonly',
      ReadableStreamDefaultController: 'readonly',
      ReadableStreamDefaultReader: 'readonly',
      registerProcessor: 'readonly',
      RelativeOrientationSensor: 'readonly',
      RemotePlayback: 'readonly',
      removeEventListener: 'readonly',
      reportError: 'readonly',
      ReportingObserver: 'readonly',
      Request: 'readonly',
      requestAnimationFrame: 'readonly',
      requestIdleCallback: 'readonly',
      resizeBy: 'readonly',
      ResizeObserver: 'readonly',
      ResizeObserverEntry: 'readonly',
      ResizeObserverSize: 'readonly',
      resizeTo: 'readonly',
      Response: 'readonly',
      RTCCertificate: 'readonly',
      RTCDataChannel: 'readonly',
      RTCDataChannelEvent: 'readonly',
      RTCDtlsTransport: 'readonly',
      RTCDTMFSender: 'readonly',
      RTCDTMFToneChangeEvent: 'readonly',
      RTCEncodedAudioFrame: 'readonly',
      RTCEncodedVideoFrame: 'readonly',
      RTCError: 'readonly',
      RTCErrorEvent: 'readonly',
      RTCIceCandidate: 'readonly',
      RTCIceTransport: 'readonly',
      RTCPeerConnection: 'readonly',
      RTCPeerConnectionIceErrorEvent: 'readonly',
      RTCPeerConnectionIceEvent: 'readonly',
      RTCRtpReceiver: 'readonly',
      RTCRtpScriptTransform: 'readonly',
      RTCRtpSender: 'readonly',
      RTCRtpTransceiver: 'readonly',
      RTCSctpTransport: 'readonly',
      RTCSessionDescription: 'readonly',
      RTCStatsReport: 'readonly',
      RTCTrackEvent: 'readonly',
      sampleRate: 'readonly',
      scheduler: 'readonly',
      Scheduler: 'readonly',
      Scheduling: 'readonly',
      screen: 'readonly',
      Screen: 'readonly',
      ScreenDetailed: 'readonly',
      ScreenDetails: 'readonly',
      screenLeft: 'readonly',
      ScreenOrientation: 'readonly',
      screenTop: 'readonly',
      screenX: 'readonly',
      screenY: 'readonly',
      ScriptProcessorNode: 'readonly',
      scroll: 'readonly',
      scrollbars: 'readonly',
      scrollBy: 'readonly',
      ScrollTimeline: 'readonly',
      scrollTo: 'readonly',
      scrollX: 'readonly',
      scrollY: 'readonly',
      SecurityPolicyViolationEvent: 'readonly',
      Selection: 'readonly',
      self: 'readonly',
      Sensor: 'readonly',
      SensorErrorEvent: 'readonly',
      Serial: 'readonly',
      SerialPort: 'readonly',
      ServiceWorker: 'readonly',
      ServiceWorkerContainer: 'readonly',
      ServiceWorkerRegistration: 'readonly',
      sessionStorage: 'readonly',
      setInterval: 'readonly',
      setTimeout: 'readonly',
      ShadowRoot: 'readonly',
      sharedStorage: 'readonly',
      SharedStorage: 'readonly',
      SharedStorageWorklet: 'readonly',
      SharedWorker: 'readonly',
      showDirectoryPicker: 'readonly',
      showOpenFilePicker: 'readonly',
      showSaveFilePicker: 'readonly',
      SnapEvent: 'readonly',
      SourceBuffer: 'readonly',
      SourceBufferList: 'readonly',
      speechSynthesis: 'readonly',
      SpeechSynthesis: 'readonly',
      SpeechSynthesisErrorEvent: 'readonly',
      SpeechSynthesisEvent: 'readonly',
      SpeechSynthesisUtterance: 'readonly',
      SpeechSynthesisVoice: 'readonly',
      StaticRange: 'readonly',
      status: 'readonly',
      statusbar: 'readonly',
      StereoPannerNode: 'readonly',
      stop: 'readonly',
      Storage: 'readonly',
      StorageBucket: 'readonly',
      StorageBucketManager: 'readonly',
      StorageEvent: 'readonly',
      StorageManager: 'readonly',
      structuredClone: 'readonly',
      styleMedia: 'readonly',
      StylePropertyMap: 'readonly',
      StylePropertyMapReadOnly: 'readonly',
      StyleSheet: 'readonly',
      StyleSheetList: 'readonly',
      SubmitEvent: 'readonly',
      SubtleCrypto: 'readonly',
      SVGAElement: 'readonly',
      SVGAngle: 'readonly',
      SVGAnimatedAngle: 'readonly',
      SVGAnimatedBoolean: 'readonly',
      SVGAnimatedEnumeration: 'readonly',
      SVGAnimatedInteger: 'readonly',
      SVGAnimatedLength: 'readonly',
      SVGAnimatedLengthList: 'readonly',
      SVGAnimatedNumber: 'readonly',
      SVGAnimatedNumberList: 'readonly',
      SVGAnimatedPreserveAspectRatio: 'readonly',
      SVGAnimatedRect: 'readonly',
      SVGAnimatedString: 'readonly',
      SVGAnimatedTransformList: 'readonly',
      SVGAnimateElement: 'readonly',
      SVGAnimateMotionElement: 'readonly',
      SVGAnimateTransformElement: 'readonly',
      SVGAnimationElement: 'readonly',
      SVGCircleElement: 'readonly',
      SVGClipPathElement: 'readonly',
      SVGComponentTransferFunctionElement: 'readonly',
      SVGDefsElement: 'readonly',
      SVGDescElement: 'readonly',
      SVGElement: 'readonly',
      SVGEllipseElement: 'readonly',
      SVGFEBlendElement: 'readonly',
      SVGFEColorMatrixElement: 'readonly',
      SVGFEComponentTransferElement: 'readonly',
      SVGFECompositeElement: 'readonly',
      SVGFEConvolveMatrixElement: 'readonly',
      SVGFEDiffuseLightingElement: 'readonly',
      SVGFEDisplacementMapElement: 'readonly',
      SVGFEDistantLightElement: 'readonly',
      SVGFEDropShadowElement: 'readonly',
      SVGFEFloodElement: 'readonly',
      SVGFEFuncAElement: 'readonly',
      SVGFEFuncBElement: 'readonly',
      SVGFEFuncGElement: 'readonly',
      SVGFEFuncRElement: 'readonly',
      SVGFEGaussianBlurElement: 'readonly',
      SVGFEImageElement: 'readonly',
      SVGFEMergeElement: 'readonly',
      SVGFEMergeNodeElement: 'readonly',
      SVGFEMorphologyElement: 'readonly',
      SVGFEOffsetElement: 'readonly',
      SVGFEPointLightElement: 'readonly',
      SVGFESpecularLightingElement: 'readonly',
      SVGFESpotLightElement: 'readonly',
      SVGFETileElement: 'readonly',
      SVGFETurbulenceElement: 'readonly',
      SVGFilterElement: 'readonly',
      SVGForeignObjectElement: 'readonly',
      SVGGElement: 'readonly',
      SVGGeometryElement: 'readonly',
      SVGGradientElement: 'readonly',
      SVGGraphicsElement: 'readonly',
      SVGImageElement: 'readonly',
      SVGLength: 'readonly',
      SVGLengthList: 'readonly',
      SVGLinearGradientElement: 'readonly',
      SVGLineElement: 'readonly',
      SVGMarkerElement: 'readonly',
      SVGMaskElement: 'readonly',
      SVGMatrix: 'readonly',
      SVGMetadataElement: 'readonly',
      SVGMPathElement: 'readonly',
      SVGNumber: 'readonly',
      SVGNumberList: 'readonly',
      SVGPathElement: 'readonly',
      SVGPatternElement: 'readonly',
      SVGPoint: 'readonly',
      SVGPointList: 'readonly',
      SVGPolygonElement: 'readonly',
      SVGPolylineElement: 'readonly',
      SVGPreserveAspectRatio: 'readonly',
      SVGRadialGradientElement: 'readonly',
      SVGRect: 'readonly',
      SVGRectElement: 'readonly',
      SVGScriptElement: 'readonly',
      SVGSetElement: 'readonly',
      SVGStopElement: 'readonly',
      SVGStringList: 'readonly',
      SVGStyleElement: 'readonly',
      SVGSVGElement: 'readonly',
      SVGSwitchElement: 'readonly',
      SVGSymbolElement: 'readonly',
      SVGTextContentElement: 'readonly',
      SVGTextElement: 'readonly',
      SVGTextPathElement: 'readonly',
      SVGTextPositioningElement: 'readonly',
      SVGTitleElement: 'readonly',
      SVGTransform: 'readonly',
      SVGTransformList: 'readonly',
      SVGTSpanElement: 'readonly',
      SVGUnitTypes: 'readonly',
      SVGUseElement: 'readonly',
      SVGViewElement: 'readonly',
      SyncManager: 'readonly',
      TaskAttributionTiming: 'readonly',
      TaskController: 'readonly',
      TaskPriorityChangeEvent: 'readonly',
      TaskSignal: 'readonly',
      TEMPORARY: 'readonly',
      Text: 'readonly',
      TextDecoder: 'readonly',
      TextDecoderStream: 'readonly',
      TextEncoder: 'readonly',
      TextEncoderStream: 'readonly',
      TextEvent: 'readonly',
      TextFormat: 'readonly',
      TextFormatUpdateEvent: 'readonly',
      TextMetrics: 'readonly',
      TextTrack: 'readonly',
      TextTrackCue: 'readonly',
      TextTrackCueList: 'readonly',
      TextTrackList: 'readonly',
      TextUpdateEvent: 'readonly',
      TimeEvent: 'readonly',
      TimeRanges: 'readonly',
      ToggleEvent: 'readonly',
      toolbar: 'readonly',
      top: 'readonly',
      Touch: 'readonly',
      TouchEvent: 'readonly',
      TouchList: 'readonly',
      TrackEvent: 'readonly',
      TransformStream: 'readonly',
      TransformStreamDefaultController: 'readonly',
      TransitionEvent: 'readonly',
      TreeWalker: 'readonly',
      TrustedHTML: 'readonly',
      TrustedScript: 'readonly',
      TrustedScriptURL: 'readonly',
      TrustedTypePolicy: 'readonly',
      TrustedTypePolicyFactory: 'readonly',
      trustedTypes: 'readonly',
      UIEvent: 'readonly',
      URL: 'readonly',
      URLPattern: 'readonly',
      URLSearchParams: 'readonly',
      USB: 'readonly',
      USBAlternateInterface: 'readonly',
      USBConfiguration: 'readonly',
      USBConnectionEvent: 'readonly',
      USBDevice: 'readonly',
      USBEndpoint: 'readonly',
      USBInterface: 'readonly',
      USBInTransferResult: 'readonly',
      USBIsochronousInTransferPacket: 'readonly',
      USBIsochronousInTransferResult: 'readonly',
      USBIsochronousOutTransferPacket: 'readonly',
      USBIsochronousOutTransferResult: 'readonly',
      USBOutTransferResult: 'readonly',
      UserActivation: 'readonly',
      ValidityState: 'readonly',
      VideoColorSpace: 'readonly',
      VideoDecoder: 'readonly',
      VideoEncoder: 'readonly',
      VideoFrame: 'readonly',
      VideoPlaybackQuality: 'readonly',
      ViewTimeline: 'readonly',
      ViewTransition: 'readonly',
      ViewTransitionTypeSet: 'readonly',
      VirtualKeyboard: 'readonly',
      VirtualKeyboardGeometryChangeEvent: 'readonly',
      VisibilityStateEntry: 'readonly',
      visualViewport: 'readonly',
      VisualViewport: 'readonly',
      VTTCue: 'readonly',
      VTTRegion: 'readonly',
      WakeLock: 'readonly',
      WakeLockSentinel: 'readonly',
      WaveShaperNode: 'readonly',
      WebAssembly: 'readonly',
      WebGL2RenderingContext: 'readonly',
      WebGLActiveInfo: 'readonly',
      WebGLBuffer: 'readonly',
      WebGLContextEvent: 'readonly',
      WebGLFramebuffer: 'readonly',
      WebGLObject: 'readonly',
      WebGLProgram: 'readonly',
      WebGLQuery: 'readonly',
      WebGLRenderbuffer: 'readonly',
      WebGLRenderingContext: 'readonly',
      WebGLSampler: 'readonly',
      WebGLShader: 'readonly',
      WebGLShaderPrecisionFormat: 'readonly',
      WebGLSync: 'readonly',
      WebGLTexture: 'readonly',
      WebGLTransformFeedback: 'readonly',
      WebGLUniformLocation: 'readonly',
      WebGLVertexArrayObject: 'readonly',
      WebSocket: 'readonly',
      WebSocketError: 'readonly',
      WebSocketStream: 'readonly',
      WebTransport: 'readonly',
      WebTransportBidirectionalStream: 'readonly',
      WebTransportDatagramDuplexStream: 'readonly',
      WebTransportError: 'readonly',
      WebTransportReceiveStream: 'readonly',
      WebTransportSendStream: 'readonly',
      WGSLLanguageFeatures: 'readonly',
      WheelEvent: 'readonly',
      window: 'readonly',
      Window: 'readonly',
      WindowControlsOverlay: 'readonly',
      WindowControlsOverlayGeometryChangeEvent: 'readonly',
      Worker: 'readonly',
      Worklet: 'readonly',
      WorkletGlobalScope: 'readonly',
      WritableStream: 'readonly',
      WritableStreamDefaultController: 'readonly',
      WritableStreamDefaultWriter: 'readonly',
      XMLDocument: 'readonly',
      XMLHttpRequest: 'readonly',
      XMLHttpRequestEventTarget: 'readonly',
      XMLHttpRequestUpload: 'readonly',
      XMLSerializer: 'readonly',
      XPathEvaluator: 'readonly',
      XPathExpression: 'readonly',
      XPathResult: 'readonly',
      XRAnchor: 'readonly',
      XRAnchorSet: 'readonly',
      XRBoundedReferenceSpace: 'readonly',
      XRCamera: 'readonly',
      XRCPUDepthInformation: 'readonly',
      XRDepthInformation: 'readonly',
      XRDOMOverlayState: 'readonly',
      XRFrame: 'readonly',
      XRHand: 'readonly',
      XRHitTestResult: 'readonly',
      XRHitTestSource: 'readonly',
      XRInputSource: 'readonly',
      XRInputSourceArray: 'readonly',
      XRInputSourceEvent: 'readonly',
      XRInputSourcesChangeEvent: 'readonly',
      XRJointPose: 'readonly',
      XRJointSpace: 'readonly',
      XRLayer: 'readonly',
      XRLightEstimate: 'readonly',
      XRLightProbe: 'readonly',
      XRPose: 'readonly',
      XRRay: 'readonly',
      XRReferenceSpace: 'readonly',
      XRReferenceSpaceEvent: 'readonly',
      XRRenderState: 'readonly',
      XRRigidTransform: 'readonly',
      XRSession: 'readonly',
      XRSessionEvent: 'readonly',
      XRSpace: 'readonly',
      XRSystem: 'readonly',
      XRTransientInputHitTestResult: 'readonly',
      XRTransientInputHitTestSource: 'readonly',
      XRView: 'readonly',
      XRViewerPose: 'readonly',
      XRViewport: 'readonly',
      XRWebGLBinding: 'readonly',
      XRWebGLDepthInformation: 'readonly',
      XRWebGLLayer: 'readonly',
      XSLTProcessor: 'readonly',
      __dirname: 'readonly',
      __filename: 'readonly',
      Buffer: 'readonly',
      clearImmediate: 'readonly',
      process: 'readonly',
      setImmediate: 'readonly',
    },
    ignorePatterns: [
      '**/logs',
      '**/*.log',
      '**/npm-debug.log*',
      '**/yarn-debug.log*',
      '**/yarn-error.log*',
      '**/pnpm-debug.log*',
      '**/lerna-debug.log*',
      '**/node_modules',
      '**/dist',
      '**/dist-ssr',
      '**/*.local',
      '.vscode/*',
      '!.vscode/extensions.json',
      '**/.idea',
      '**/.DS_Store',
      '**/*.suo',
      '**/*.ntvs*',
      '**/*.njsproj',
      '**/*.sln',
      '**/*.sw?',
      '**/package-lock.json',
      '**/yarn.lock',
      '**/pnpm-lock.yaml',
      '**/bun.lockb',
      '**/output',
      '**/coverage',
      '**/temp',
      '**/.temp',
      '**/tmp',
      '**/.tmp',
      '**/.history',
      '**/.vitepress/cache',
      '**/.nuxt',
      '**/.next',
      '**/.svelte-kit',
      '**/.vercel',
      '**/.changeset',
      '**/.cache',
      '**/.output',
      '**/.vite-inspect',
      '**/.yarn',
      '**/vite.config.*.timestamp-*',
      '**/CHANGELOG*.md',
      '**/*.min.*',
      '**/LICENSE*',
      '**/__snapshots__',
      '**/auto-import?(s).d.ts',
      '**/components.d.ts',
    ],
    rules: {
      'accessor-pairs': [
        'error',
        {
          enforceForClassMembers: true,
          setWithoutGet: true,
        },
      ],
      'antfu/no-top-level-await': 'error',
      'array-callback-return': 'error',
      'block-scoped-var': 'error',
      'constructor-super': 'error',
      'default-case-last': 'error',
      '@typescript-eslint/dot-notation': [
        'error',
        {
          allowKeywords: true,
        },
      ],
      eqeqeq: ['error', 'smart'],
      'new-cap': [
        'error',
        {
          capIsNew: false,
          newIsCap: true,
          properties: true,
        },
      ],
      'no-alert': 'error',
      'no-array-constructor': 'error',
      'no-async-promise-executor': 'error',
      'no-caller': 'error',
      'no-case-declarations': 'error',
      'no-class-assign': 'error',
      'no-compare-neg-zero': 'error',
      'no-cond-assign': ['error', 'always'],
      'no-console': [
        'error',
        {
          allow: ['warn', 'error'],
        },
      ],
      'no-const-assign': 'error',
      'no-control-regex': 'error',
      'no-debugger': 'error',
      'no-delete-var': 'error',
      'no-dupe-class-members': 'error',
      'no-dupe-keys': 'error',
      'no-duplicate-case': 'error',
      'no-empty': [
        'error',
        {
          allowEmptyCatch: true,
        },
      ],
      'no-empty-character-class': 'error',
      'no-empty-pattern': 'error',
      'no-eval': 'error',
      'no-ex-assign': 'error',
      'no-extend-native': 'error',
      'no-extra-bind': 'error',
      'no-extra-boolean-cast': 'error',
      'no-fallthrough': 'error',
      'no-func-assign': 'error',
      'no-global-assign': 'error',
      'no-import-assign': 'error',
      'no-invalid-regexp': 'error',
      'no-irregular-whitespace': 'error',
      'no-iterator': 'error',
      'no-labels': [
        'error',
        {
          allowLoop: false,
          allowSwitch: false,
        },
      ],
      'no-lone-blocks': 'error',
      'no-loss-of-precision': 'error',
      'no-misleading-character-class': 'error',
      'no-multi-str': 'error',
      'no-new': 'error',
      'no-new-func': 'error',
      'no-new-native-nonconstructor': 'error',
      'no-new-wrappers': 'error',
      'no-obj-calls': 'error',
      'no-proto': 'error',
      'no-prototype-builtins': 'error',
      'no-redeclare': [
        'error',
        {
          builtinGlobals: false,
        },
      ],
      'no-regex-spaces': 'error',
      'no-restricted-globals': [
        'error',
        {
          message: 'Use `globalThis` instead.',
          name: 'global',
        },
        {
          message: 'Use `globalThis` instead.',
          name: 'self',
        },
      ],
      'no-self-assign': [
        'error',
        {
          props: true,
        },
      ],
      'no-self-compare': 'error',
      'no-sequences': 'error',
      'no-shadow-restricted-names': 'error',
      'no-sparse-arrays': 'error',
      'no-template-curly-in-string': 'error',
      'no-this-before-super': 'error',
      'no-throw-literal': 'error',
      'no-undef': 'error',
      'no-unexpected-multiline': 'error',
      'no-unmodified-loop-condition': 'error',
      'no-unneeded-ternary': [
        'error',
        {
          defaultAssignment: false,
        },
      ],
      'no-unreachable': 'error',
      'no-unsafe-finally': 'error',
      'no-unsafe-negation': 'error',
      'no-unused-expressions': [
        'error',
        {
          allowShortCircuit: true,
          allowTaggedTemplates: true,
          allowTernary: true,
        },
      ],
      'no-unused-vars': [
        'error',
        {
          args: 'none',
          caughtErrors: 'none',
          ignoreRestSiblings: true,
          vars: 'all',
        },
      ],
      'no-use-before-define': [
        'error',
        {
          classes: false,
          functions: false,
          variables: true,
        },
      ],
      'no-useless-backreference': 'error',
      'no-useless-call': 'error',
      'no-useless-catch': 'error',
      'no-useless-computed-key': 'error',
      'no-useless-constructor': 'error',
      'no-useless-rename': 'error',
      'no-useless-return': 'error',
      'no-var': 'error',
      'no-with': 'error',
      'prefer-const': [
        'error',
        {
          destructuring: 'all',
          ignoreReadBeforeAssign: true,
        },
      ],
      'prefer-exponentiation-operator': 'error',
      'prefer-promise-reject-errors': 'error',
      'prefer-rest-params': 'error',
      'prefer-spread': 'error',
      'prefer-template': 'error',
      'symbol-description': 'error',
      'unicode-bom': ['error', 'never'],
      'unused-imports/no-unused-imports': 'error',
      'unused-imports/no-unused-vars': [
        'error',
        {
          args: 'after-used',
          argsIgnorePattern: '^_',
          ignoreRestSiblings: true,
          vars: 'all',
          varsIgnorePattern: '^_',
        },
      ],
      'use-isnan': [
        'error',
        {
          enforceForIndexOf: true,
          enforceForSwitchCase: true,
        },
      ],
      'valid-typeof': [
        'error',
        {
          requireStringLiterals: true,
        },
      ],
      'vars-on-top': 'error',
      yoda: ['error', 'never'],
      'eslint-comments/no-aggregating-enable': 'error',
      'eslint-comments/no-duplicate-disable': 'error',
      'eslint-comments/no-unlimited-disable': 'error',
      'eslint-comments/no-unused-enable': 'error',
      'node/handle-callback-err': ['error', '^(err|error)$'],
      'node/no-exports-assign': 'error',
      'node/no-new-require': 'error',
      'node/no-path-concat': 'error',
      'jsdoc/check-access': 'warn',
      'jsdoc/empty-tags': 'warn',
      'jsdoc/require-param-name': 'warn',
      'jsdoc/require-returns-description': 'warn',
      'antfu/import-dedupe': 'error',
      'antfu/no-import-dist': 'error',
      'antfu/no-import-node-modules-by-path': 'error',
      'import/first': 'error',
      'import/no-duplicates': 'error',
      'import/no-mutable-exports': 'error',
      'import/no-named-default': 'error',
      'import/no-self-import': 'error',
      'import/no-webpack-loader-syntax': 'error',
      'command/command': 'error',
      'perfectionist/sort-exports': [
        'error',
        {
          order: 'asc',
          type: 'natural',
        },
      ],
      'perfectionist/sort-named-exports': [
        'error',
        {
          order: 'asc',
          type: 'natural',
        },
      ],
      'perfectionist/sort-named-imports': [
        'error',
        {
          order: 'asc',
          type: 'natural',
        },
      ],
      'unicorn/consistent-empty-array-spread': 'error',
      'unicorn/error-message': 'error',
      'unicorn/escape-case': 'error',
      'unicorn/new-for-builtins': 'error',
      'unicorn/no-instanceof-array': 'error',
      'unicorn/no-new-array': 'error',
      'unicorn/no-new-buffer': 'error',
      'unicorn/number-literal-case': 'error',
      'unicorn/prefer-dom-node-text-content': 'error',
      'unicorn/prefer-includes': 'error',
      'unicorn/prefer-node-protocol': 'error',
      'unicorn/prefer-number-properties': 'error',
      'unicorn/prefer-string-starts-ends-with': 'error',
      'unicorn/prefer-type-error': 'error',
      'unicorn/throw-new-error': 'error',
      '@stylistic/array-bracket-spacing': ['error', 'never'],
      '@stylistic/arrow-parens': [
        'error',
        'as-needed',
        {
          requireForBlockBody: true,
        },
      ],
      '@stylistic/arrow-spacing': [
        'error',
        {
          after: true,
          before: true,
        },
      ],
      '@stylistic/block-spacing': ['error', 'always'],
      '@stylistic/brace-style': [
        'error',
        'stroustrup',
        {
          allowSingleLine: true,
        },
      ],
      '@stylistic/comma-dangle': ['error', 'always-multiline'],
      '@stylistic/comma-spacing': [
        'error',
        {
          after: true,
          before: false,
        },
      ],
      '@stylistic/comma-style': ['error', 'last'],
      '@stylistic/computed-property-spacing': [
        'error',
        'never',
        {
          enforceForClassMembers: true,
        },
      ],
      '@stylistic/dot-location': ['error', 'property'],
      '@stylistic/eol-last': 'error',
      '@stylistic/indent': [
        'error',
        2,
        {
          ArrayExpression: 1,
          CallExpression: {
            arguments: 1,
          },
          flatTernaryExpressions: false,
          FunctionDeclaration: {
            body: 1,
            parameters: 1,
          },
          FunctionExpression: {
            body: 1,
            parameters: 1,
          },
          ignoreComments: false,
          ignoredNodes: [
            'TSUnionType',
            'TSIntersectionType',
            'TSTypeParameterInstantiation',
            'FunctionExpression > .params[decorators.length > 0]',
            'FunctionExpression > .params > :matches(Decorator, :not(:first-child))',
          ],
          ImportDeclaration: 1,
          MemberExpression: 1,
          ObjectExpression: 1,
          offsetTernaryExpressions: true,
          outerIIFEBody: 1,
          SwitchCase: 1,
          tabLength: 2,
          VariableDeclarator: 1,
        },
      ],
      '@stylistic/indent-binary-ops': ['error', 2],
      '@stylistic/key-spacing': [
        'error',
        {
          afterColon: true,
          beforeColon: false,
        },
      ],
      '@stylistic/keyword-spacing': [
        'error',
        {
          after: true,
          before: true,
        },
      ],
      '@stylistic/lines-between-class-members': [
        'error',
        'always',
        {
          exceptAfterSingleLine: true,
        },
      ],
      '@stylistic/max-statements-per-line': [
        'error',
        {
          max: 1,
        },
      ],
      '@stylistic/member-delimiter-style': [
        'error',
        {
          multiline: {
            delimiter: 'none',
            requireLast: false,
          },
          multilineDetection: 'brackets',
          overrides: {
            interface: {
              multiline: {
                delimiter: 'none',
                requireLast: false,
              },
            },
          },
          singleline: {
            delimiter: 'comma',
          },
        },
      ],
      '@stylistic/multiline-ternary': ['error', 'always-multiline'],
      '@stylistic/new-parens': 'error',
      '@stylistic/no-extra-parens': ['error', 'functions'],
      '@stylistic/no-floating-decimal': 'error',
      '@stylistic/no-mixed-operators': [
        'error',
        {
          allowSamePrecedence: true,
          groups: [
            ['==', '!=', '===', '!==', '>', '>=', '<', '<='],
            ['&&', '||'],
            ['in', 'instanceof'],
          ],
        },
      ],
      '@stylistic/no-mixed-spaces-and-tabs': 'error',
      '@stylistic/no-multi-spaces': 'error',
      '@stylistic/no-multiple-empty-lines': [
        'error',
        {
          max: 1,
          maxBOF: 0,
          maxEOF: 0,
        },
      ],
      '@stylistic/no-tabs': 'error',
      '@stylistic/no-trailing-spaces': 'error',
      '@stylistic/no-whitespace-before-property': 'error',
      '@stylistic/object-curly-spacing': ['error', 'always'],
      '@stylistic/operator-linebreak': ['error', 'before'],
      '@stylistic/padded-blocks': [
        'error',
        {
          blocks: 'never',
          classes: 'never',
          switches: 'never',
        },
      ],
      '@stylistic/quote-props': ['error', 'consistent-as-needed'],
      '@stylistic/quotes': [
        'error',
        'single',
        {
          allowTemplateLiterals: true,
          avoidEscape: false,
        },
      ],
      '@stylistic/rest-spread-spacing': ['error', 'never'],
      '@stylistic/semi': ['error', 'never'],
      '@stylistic/semi-spacing': [
        'error',
        {
          after: true,
          before: false,
        },
      ],
      '@stylistic/space-before-blocks': ['error', 'always'],
      '@stylistic/space-before-function-paren': [
        'error',
        {
          anonymous: 'always',
          asyncArrow: 'always',
          named: 'never',
        },
      ],
      '@stylistic/space-in-parens': ['error', 'never'],
      '@stylistic/space-infix-ops': 'error',
      '@stylistic/space-unary-ops': [
        'error',
        {
          nonwords: false,
          words: true,
        },
      ],
      '@stylistic/spaced-comment': [
        'error',
        'always',
        {
          block: {
            balanced: true,
            exceptions: ['*'],
            markers: ['!'],
          },
          line: {
            exceptions: ['/', '#'],
            markers: ['/'],
          },
        },
      ],
      '@stylistic/template-curly-spacing': 'error',
      '@stylistic/template-tag-spacing': ['error', 'never'],
      '@stylistic/type-annotation-spacing': ['error', {}],
      '@stylistic/type-generic-spacing': 'error',
      '@stylistic/type-named-tuple-spacing': 'error',
      '@stylistic/wrap-iife': [
        'error',
        'any',
        {
          functionPrototypeMethods: true,
        },
      ],
      '@stylistic/yield-star-spacing': ['error', 'both'],
      '@stylistic/jsx-closing-bracket-location': 'error',
      '@stylistic/jsx-closing-tag-location': 'error',
      '@stylistic/jsx-curly-brace-presence': [
        'error',
        {
          propElementValues: 'always',
        },
      ],
      '@stylistic/jsx-curly-newline': 'error',
      '@stylistic/jsx-curly-spacing': ['error', 'never'],
      '@stylistic/jsx-equals-spacing': 'error',
      '@stylistic/jsx-first-prop-new-line': 'error',
      '@stylistic/jsx-function-call-newline': ['error', 'multiline'],
      '@stylistic/jsx-indent-props': ['error', 2],
      '@stylistic/jsx-max-props-per-line': [
        'error',
        {
          maximum: 1,
          when: 'multiline',
        },
      ],
      '@stylistic/jsx-one-expression-per-line': [
        'error',
        {
          allow: 'single-child',
        },
      ],
      '@stylistic/jsx-quotes': 'error',
      '@stylistic/jsx-tag-spacing': [
        'error',
        {
          afterOpening: 'never',
          beforeClosing: 'never',
          beforeSelfClosing: 'always',
          closingSlash: 'never',
        },
      ],
      '@stylistic/jsx-wrap-multilines': [
        'error',
        {
          arrow: 'parens-new-line',
          assignment: 'parens-new-line',
          condition: 'parens-new-line',
          declaration: 'parens-new-line',
          logical: 'parens-new-line',
          prop: 'parens-new-line',
          propertyValue: 'parens-new-line',
          return: 'parens-new-line',
        },
      ],
      'antfu/consistent-chaining': 'error',
      'antfu/consistent-list-newline': 'error',
      'antfu/curly': 'error',
      'antfu/if-newline': 'error',
      'regexp/confusing-quantifier': 'warn',
      'regexp/control-character-escape': 'error',
      'regexp/match-any': 'error',
      'regexp/negation': 'error',
      'regexp/no-contradiction-with-assertion': 'error',
      'regexp/no-dupe-characters-character-class': 'error',
      'regexp/no-dupe-disjunctions': 'error',
      'regexp/no-empty-alternative': 'warn',
      'regexp/no-empty-capturing-group': 'error',
      'regexp/no-empty-character-class': 'error',
      'regexp/no-empty-group': 'error',
      'regexp/no-empty-lookarounds-assertion': 'error',
      'regexp/no-empty-string-literal': 'error',
      'regexp/no-escape-backspace': 'error',
      'regexp/no-extra-lookaround-assertions': 'error',
      'regexp/no-invalid-regexp': 'error',
      'regexp/no-invisible-character': 'error',
      'regexp/no-lazy-ends': 'warn',
      'regexp/no-legacy-features': 'error',
      'regexp/no-misleading-capturing-group': 'error',
      'regexp/no-misleading-unicode-character': 'error',
      'regexp/no-missing-g-flag': 'error',
      'regexp/no-non-standard-flag': 'error',
      'regexp/no-obscure-range': 'error',
      'regexp/no-optional-assertion': 'error',
      'regexp/no-potentially-useless-backreference': 'warn',
      'regexp/no-super-linear-backtracking': 'error',
      'regexp/no-trivially-nested-assertion': 'error',
      'regexp/no-trivially-nested-quantifier': 'error',
      'regexp/no-unused-capturing-group': 'error',
      'regexp/no-useless-assertions': 'error',
      'regexp/no-useless-backreference': 'error',
      'regexp/no-useless-character-class': 'error',
      'regexp/no-useless-dollar-replacements': 'error',
      'regexp/no-useless-escape': 'error',
      'regexp/no-useless-flag': 'warn',
      'regexp/no-useless-lazy': 'error',
      'regexp/no-useless-non-capturing-group': 'error',
      'regexp/no-useless-quantifier': 'error',
      'regexp/no-useless-range': 'error',
      'regexp/no-useless-set-operand': 'error',
      'regexp/no-useless-string-literal': 'error',
      'regexp/no-useless-two-nums-quantifier': 'error',
      'regexp/no-zero-quantifier': 'error',
      'regexp/optimal-lookaround-quantifier': 'warn',
      'regexp/optimal-quantifier-concatenation': 'error',
      'regexp/prefer-character-class': 'error',
      'regexp/prefer-d': 'error',
      'regexp/prefer-plus-quantifier': 'error',
      'regexp/prefer-predefined-assertion': 'error',
      'regexp/prefer-question-quantifier': 'error',
      'regexp/prefer-range': 'error',
      'regexp/prefer-set-operation': 'error',
      'regexp/prefer-star-quantifier': 'error',
      'regexp/prefer-unicode-codepoint-escapes': 'error',
      'regexp/prefer-w': 'error',
      'regexp/simplify-set-operations': 'error',
      'regexp/sort-flags': 'error',
      'regexp/strict': 'error',
      'regexp/use-ignore-case': 'error',
      curly: ['error', 'all'],
      '@stylistic/function-call-spacing': ['error', 'never'],
    },
    overrides: [
      {
        files: ['**/*.?([cm])ts', '**/*.?([cm])tsx'],
        rules: {
          'constructor-super': 'off',
          'getter-return': 'off',
          'no-class-assign': 'off',
          'no-const-assign': 'off',
          'no-dupe-keys': 'off',
          'no-func-assign': 'off',
          'no-import-assign': 'off',
          'no-new-native-nonconstructor': 'off',
          'no-obj-calls': 'off',
          'no-redeclare': [
            'error',
            {
              builtinGlobals: false,
            },
          ],
          'no-setter-return': 'off',
          'no-this-before-super': 'off',
          'no-undef': 'off',
          'no-unreachable': 'off',
          'no-unsafe-negation': 'off',
          'prefer-const': 'error',
          '@typescript-eslint/ban-ts-comment': [
            'error',
            {
              'ts-expect-error': 'allow-with-description',
            },
          ],
          '@typescript-eslint/no-duplicate-enum-values': 'error',
          '@typescript-eslint/no-dynamic-delete': 'off',
          '@typescript-eslint/no-empty-object-type': [
            'error',
            {
              allowInterfaces: 'always',
            },
          ],
          '@typescript-eslint/no-explicit-any': 'off',
          '@typescript-eslint/no-extra-non-null-assertion': 'error',
          '@typescript-eslint/no-extraneous-class': 'off',
          '@typescript-eslint/no-invalid-void-type': 'off',
          '@typescript-eslint/no-misused-new': 'error',
          '@typescript-eslint/no-namespace': 'error',
          '@typescript-eslint/no-non-null-asserted-nullish-coalescing': 'error',
          '@typescript-eslint/no-non-null-asserted-optional-chain': 'error',
          '@typescript-eslint/no-non-null-assertion': 'off',
          '@typescript-eslint/no-require-imports': 'error',
          '@typescript-eslint/no-this-alias': 'error',
          '@typescript-eslint/no-unnecessary-type-constraint': 'error',
          '@typescript-eslint/no-unsafe-declaration-merging': 'error',
          '@typescript-eslint/no-unsafe-function-type': 'error',
          'no-unused-expressions': [
            'error',
            {
              allowShortCircuit: true,
              allowTaggedTemplates: true,
              allowTernary: true,
            },
          ],
          'no-unused-vars': 'off',
          'no-useless-constructor': 'off',
          '@typescript-eslint/no-wrapper-object-types': 'error',
          '@typescript-eslint/prefer-as-const': 'error',
          '@typescript-eslint/prefer-literal-enum-member': 'error',
          '@typescript-eslint/prefer-namespace-keyword': 'error',
          '@typescript-eslint/triple-slash-reference': 'off',
          '@typescript-eslint/unified-signatures': 'off',
          'no-use-before-define': [
            'error',
            {
              classes: false,
              functions: false,
              variables: true,
            },
          ],
          '@typescript-eslint/consistent-type-definitions': ['error', 'interface'],
          '@typescript-eslint/consistent-type-imports': [
            'error',
            {
              disallowTypeAnnotations: false,
              prefer: 'type-imports',
            },
          ],
          '@typescript-eslint/no-import-type-side-effects': 'error',
        },
      },
      {
        files: [
          '**/__tests__/**/*.?([cm])[jt]s?(x)',
          '**/*.spec.?([cm])[jt]s?(x)',
          '**/*.test.?([cm])[jt]s?(x)',
          '**/*.bench.?([cm])[jt]s?(x)',
          '**/*.benchmark.?([cm])[jt]s?(x)',
        ],
        rules: {
          'vitest/consistent-test-it': [
            'error',
            {
              fn: 'it',
              withinDescribe: 'it',
            },
          ],
          'vitest/no-identical-title': 'error',
          'vitest/no-import-node-test': 'error',
          'vitest/prefer-hooks-in-order': 'error',
          'vitest/prefer-lowercase-title': 'error',
          'antfu/no-top-level-await': 'off',
          'no-unused-expressions': 'off',
          '@typescript-eslint/explicit-function-return-type': 'off',
        },
        jsPlugins: ['eslint-plugin-antfu'],
        plugins: ['vitest'],
      },
      {
        files: ['**/*.json', '**/*.json5', '**/*.jsonc'],
        rules: {
          'jsonc/no-bigint-literals': 'error',
          'jsonc/no-binary-expression': 'error',
          'jsonc/no-binary-numeric-literals': 'error',
          'jsonc/no-dupe-keys': 'error',
          'jsonc/no-escape-sequence-in-identifier': 'error',
          'jsonc/no-floating-decimal': 'error',
          'jsonc/no-hexadecimal-numeric-literals': 'error',
          'jsonc/no-infinity': 'error',
          'jsonc/no-multi-str': 'error',
          'jsonc/no-nan': 'error',
          'jsonc/no-number-props': 'error',
          'jsonc/no-numeric-separators': 'error',
          'jsonc/no-octal': 'error',
          'jsonc/no-octal-escape': 'error',
          'jsonc/no-octal-numeric-literals': 'error',
          'jsonc/no-parenthesized': 'error',
          'jsonc/no-plus-sign': 'error',
          'jsonc/no-regexp-literals': 'error',
          'jsonc/no-sparse-arrays': 'error',
          'jsonc/no-template-literals': 'error',
          'jsonc/no-undefined-value': 'error',
          'jsonc/no-unicode-codepoint-escapes': 'error',
          'jsonc/no-useless-escape': 'error',
          'jsonc/space-unary-ops': 'error',
          'jsonc/valid-json-number': 'error',
          'jsonc/vue-custom-block/no-parsing-error': 'error',
          'jsonc/array-bracket-spacing': ['error', 'never'],
          'jsonc/comma-dangle': ['error', 'never'],
          'jsonc/comma-style': ['error', 'last'],
          'jsonc/indent': ['error', 2],
          'jsonc/key-spacing': [
            'error',
            {
              afterColon: true,
              beforeColon: false,
            },
          ],
          'jsonc/object-curly-newline': [
            'error',
            {
              consistent: true,
              multiline: true,
            },
          ],
          'jsonc/object-curly-spacing': ['error', 'always'],
          'jsonc/object-property-newline': [
            'error',
            {
              allowMultiplePropertiesPerLine: true,
            },
          ],
          'jsonc/quote-props': 'error',
          'jsonc/quotes': 'error',
        },
        jsPlugins: ['eslint-plugin-jsonc'],
      },
      {
        files: ['**/package.json'],
        rules: {
          'jsonc/sort-array-values': [
            'error',
            {
              order: {
                type: 'asc',
              },
              pathPattern: '^files$',
            },
          ],
          'jsonc/sort-keys': [
            'error',
            {
              order: [
                'publisher',
                'name',
                'displayName',
                'type',
                'version',
                'private',
                'packageManager',
                'description',
                'author',
                'contributors',
                'license',
                'funding',
                'homepage',
                'repository',
                'bugs',
                'keywords',
                'categories',
                'sideEffects',
                'exports',
                'main',
                'module',
                'unpkg',
                'jsdelivr',
                'types',
                'typesVersions',
                'bin',
                'icon',
                'files',
                'engines',
                'activationEvents',
                'contributes',
                'scripts',
                'peerDependencies',
                'peerDependenciesMeta',
                'dependencies',
                'optionalDependencies',
                'devDependencies',
                'pnpm',
                'overrides',
                'resolutions',
                'husky',
                'simple-git-hooks',
                'lint-staged',
                'eslintConfig',
              ],
              pathPattern: '^$',
            },
            {
              order: {
                type: 'asc',
              },
              pathPattern: '^(?:dev|peer|optional|bundled)?[Dd]ependencies(Meta)?$',
            },
            {
              order: {
                type: 'asc',
              },
              pathPattern: '^(?:resolutions|overrides|pnpm.overrides)$',
            },
            {
              order: ['types', 'import', 'require', 'default'],
              pathPattern: '^exports.*$',
            },
            {
              order: [
                'pre-commit',
                'prepare-commit-msg',
                'commit-msg',
                'post-commit',
                'pre-rebase',
                'post-rewrite',
                'post-checkout',
                'post-merge',
                'pre-push',
                'pre-auto-gc',
              ],
              pathPattern: '^(?:gitHooks|husky|simple-git-hooks)$',
            },
          ],
        },
        jsPlugins: ['eslint-plugin-jsonc'],
      },
      {
        files: ['**/tsconfig.json', '**/tsconfig.*.json'],
        rules: {
          'jsonc/sort-keys': [
            'error',
            {
              order: ['extends', 'compilerOptions', 'references', 'files', 'include', 'exclude'],
              pathPattern: '^$',
            },
            {
              order: [
                'incremental',
                'composite',
                'tsBuildInfoFile',
                'disableSourceOfProjectReferenceRedirect',
                'disableSolutionSearching',
                'disableReferencedProjectLoad',
                'target',
                'jsx',
                'jsxFactory',
                'jsxFragmentFactory',
                'jsxImportSource',
                'lib',
                'moduleDetection',
                'noLib',
                'reactNamespace',
                'useDefineForClassFields',
                'emitDecoratorMetadata',
                'experimentalDecorators',
                'baseUrl',
                'rootDir',
                'rootDirs',
                'customConditions',
                'module',
                'moduleResolution',
                'moduleSuffixes',
                'noResolve',
                'paths',
                'resolveJsonModule',
                'resolvePackageJsonExports',
                'resolvePackageJsonImports',
                'typeRoots',
                'types',
                'allowArbitraryExtensions',
                'allowImportingTsExtensions',
                'allowUmdGlobalAccess',
                'allowJs',
                'checkJs',
                'maxNodeModuleJsDepth',
                'strict',
                'strictBindCallApply',
                'strictFunctionTypes',
                'strictNullChecks',
                'strictPropertyInitialization',
                'allowUnreachableCode',
                'allowUnusedLabels',
                'alwaysStrict',
                'exactOptionalPropertyTypes',
                'noFallthroughCasesInSwitch',
                'noImplicitAny',
                'noImplicitOverride',
                'noImplicitReturns',
                'noImplicitThis',
                'noPropertyAccessFromIndexSignature',
                'noUncheckedIndexedAccess',
                'noUnusedLocals',
                'noUnusedParameters',
                'useUnknownInCatchVariables',
                'declaration',
                'declarationDir',
                'declarationMap',
                'downlevelIteration',
                'emitBOM',
                'emitDeclarationOnly',
                'importHelpers',
                'importsNotUsedAsValues',
                'inlineSourceMap',
                'inlineSources',
                'mapRoot',
                'newLine',
                'noEmit',
                'noEmitHelpers',
                'noEmitOnError',
                'outDir',
                'outFile',
                'preserveConstEnums',
                'preserveValueImports',
                'removeComments',
                'sourceMap',
                'sourceRoot',
                'stripInternal',
                'allowSyntheticDefaultImports',
                'esModuleInterop',
                'forceConsistentCasingInFileNames',
                'isolatedDeclarations',
                'isolatedModules',
                'preserveSymlinks',
                'verbatimModuleSyntax',
                'skipDefaultLibCheck',
                'skipLibCheck',
              ],
              pathPattern: '^compilerOptions$',
            },
          ],
        },
        jsPlugins: ['eslint-plugin-jsonc'],
      },
      {
        files: ['**/*.y?(a)ml'],
        rules: {
          '@stylistic/spaced-comment': 'off',
          'yml/block-mapping': 'error',
          'yml/block-sequence': 'error',
          'yml/no-empty-key': 'error',
          'yml/no-empty-sequence-entry': 'error',
          'yml/no-irregular-whitespace': 'error',
          'yml/plain-scalar': 'error',
          'yml/vue-custom-block/no-parsing-error': 'error',
          'yml/block-mapping-question-indicator-newline': 'error',
          'yml/block-sequence-hyphen-indicator-newline': 'error',
          'yml/flow-mapping-curly-newline': 'error',
          'yml/flow-mapping-curly-spacing': 'error',
          'yml/flow-sequence-bracket-newline': 'error',
          'yml/flow-sequence-bracket-spacing': 'error',
          'yml/indent': ['error', 2],
          'yml/key-spacing': 'error',
          'yml/no-tab-indent': 'error',
          'yml/quotes': [
            'error',
            {
              avoidEscape: true,
              prefer: 'single',
            },
          ],
          'yml/spaced-comment': 'error',
        },
        jsPlugins: ['@stylistic/eslint-plugin', 'eslint-plugin-yml'],
      },
      {
        files: ['**/*.toml'],
        rules: {
          '@stylistic/spaced-comment': 'off',
          'toml/comma-style': 'error',
          'toml/keys-order': 'error',
          'toml/no-space-dots': 'error',
          'toml/no-unreadable-number-separator': 'error',
          'toml/precision-of-fractional-seconds': 'error',
          'toml/precision-of-integer': 'error',
          'toml/tables-order': 'error',
          'toml/vue-custom-block/no-parsing-error': 'error',
          'toml/array-bracket-newline': 'error',
          'toml/array-bracket-spacing': 'error',
          'toml/array-element-newline': 'error',
          'toml/indent': ['error', 2],
          'toml/inline-table-curly-spacing': 'error',
          'toml/key-spacing': 'error',
          'toml/padding-line-between-pairs': 'error',
          'toml/padding-line-between-tables': 'error',
          'toml/quoted-keys': 'error',
          'toml/spaced-comment': 'error',
          'toml/table-bracket-spacing': 'error',
        },
        jsPlugins: ['@stylistic/eslint-plugin', 'eslint-plugin-toml'],
      },
      {
        files: ['**/*.md/**/*.?([cm])[jt]s?(x)'],
        rules: {
          'antfu/no-top-level-await': 'off',
          'no-alert': 'off',
          'no-console': 'off',
          'no-labels': 'off',
          'no-lone-blocks': 'off',
          'no-undef': 'off',
          'no-unused-expressions': 'off',
          'no-unused-labels': 'off',
          'no-unused-vars': 'off',
          '@stylistic/comma-dangle': 'off',
          '@stylistic/eol-last': 'off',
          '@typescript-eslint/consistent-type-imports': 'off',
          '@typescript-eslint/explicit-function-return-type': 'off',
          '@typescript-eslint/no-namespace': 'off',
          '@typescript-eslint/no-require-imports': 'off',
          'unicode-bom': 'off',
          'unused-imports/no-unused-imports': 'off',
          'unused-imports/no-unused-vars': 'off',
          'no-redeclare': 'off',
          'no-use-before-define': 'off',
        },
        jsPlugins: [
          'eslint-plugin-antfu',
          '@stylistic/eslint-plugin',
          'eslint-plugin-unused-imports',
        ],
      },
      {
        files: ['**/*.css', '**/*.{p,post}css'],
        rules: {
          'format/prettier': [
            'error',
            {
              endOfLine: 'auto',
              printWidth: 120,
              semi: false,
              singleQuote: true,
              tabWidth: 2,
              trailingComma: 'all',
              useTabs: false,
              parser: 'css',
              plugins: [],
            },
          ],
        },
        jsPlugins: ['eslint-plugin-format'],
      },
      {
        files: ['**/*.scss'],
        rules: {
          'format/prettier': [
            'error',
            {
              endOfLine: 'auto',
              printWidth: 120,
              semi: false,
              singleQuote: true,
              tabWidth: 2,
              trailingComma: 'all',
              useTabs: false,
              parser: 'scss',
              plugins: [],
            },
          ],
        },
        jsPlugins: ['eslint-plugin-format'],
      },
      {
        files: ['**/*.less'],
        rules: {
          'format/prettier': [
            'error',
            {
              endOfLine: 'auto',
              printWidth: 120,
              semi: false,
              singleQuote: true,
              tabWidth: 2,
              trailingComma: 'all',
              useTabs: false,
              parser: 'less',
              plugins: [],
            },
          ],
        },
        jsPlugins: ['eslint-plugin-format'],
      },
      {
        files: ['**/*.htm?(l)'],
        rules: {
          'format/prettier': [
            'error',
            {
              endOfLine: 'auto',
              printWidth: 120,
              semi: false,
              singleQuote: true,
              tabWidth: 2,
              trailingComma: 'all',
              useTabs: false,
              parser: 'html',
              plugins: [],
            },
          ],
        },
        jsPlugins: ['eslint-plugin-format'],
      },
      {
        files: ['**/scripts/**/*.?([cm])[jt]s?(x)'],
        rules: {
          'antfu/no-top-level-await': 'off',
          'no-console': 'off',
          '@typescript-eslint/explicit-function-return-type': 'off',
        },
        jsPlugins: ['eslint-plugin-antfu'],
      },
      {
        files: ['**/cli/**/*.?([cm])[jt]s?(x)', '**/cli.?([cm])[jt]s?(x)'],
        rules: {
          'antfu/no-top-level-await': 'off',
          'no-console': 'off',
        },
        jsPlugins: ['eslint-plugin-antfu'],
      },
      {
        files: ['**/bin/**/*', '**/bin.?([cm])[jt]s?(x)'],
        rules: {
          'antfu/no-import-dist': 'off',
          'antfu/no-import-node-modules-by-path': 'off',
        },
        jsPlugins: ['eslint-plugin-antfu'],
      },
      {
        files: ['**/*.d.?([cm])ts'],
        rules: {
          'eslint-comments/no-unlimited-disable': 'off',
          'import/no-duplicates': 'off',
          'unused-imports/no-unused-vars': 'off',
        },
        jsPlugins: ['eslint-plugin-eslint-comments', 'eslint-plugin-unused-imports'],
      },
      {
        files: ['**/*.js', '**/*.cjs'],
        rules: {
          '@typescript-eslint/no-require-imports': 'off',
        },
      },
      {
        files: ['**/*.config.?([cm])[jt]s?(x)', '**/*.config.*.?([cm])[jt]s?(x)'],
        rules: {
          'antfu/no-top-level-await': 'off',
          'no-console': 'off',
          '@typescript-eslint/explicit-function-return-type': 'off',
        },
        jsPlugins: ['eslint-plugin-antfu'],
      },
    ],
  },
  resolve: {
    alias: {
      '/@': fileURLToPath(new URL('./src', import.meta.url)),
    },
  },
  plugins: [glsl()],
  build: {
    rolldownOptions: {
      output: {
        manualChunks(id) {
          if (id.includes('node_modules/three')) {
            return 'three'
          }
          if (id.includes('node_modules/tweakpane') || id.includes('node_modules/@tweakpane')) {
            return 'tweakpane'
          }
        },
      },
    },
  },
})
